export const GET_NOW_PLAYING_SUCCESS = 'GET_NOW_PLAYING_SUCCESS';
export const GET_NOW_PLAYING_START = 'GET_NOW_PLAYING_START';
export const GET_NOW_PLAYING_FAIL = 'GET_NOW_PLAYING_FAIL';

export const GET_TRENDING_MOVIES_SUCCESS = 'GET_TRENDING_MOVIES_SUCCESS';
export const GET_TRENDING_MOVIES_START = 'GET_TRENDING_TV';
export const GET_TRENDING_MOVIES_FAIL = 'GET_TRENDING_MOVIES_FAIL';

export const GET_TRENDING_TV_SUCCESS = 'GET_TRENDING_TV_SUCCESS';
export const GET_TRENDING_TV_START = 'GET_TRENDING_TV_START';
export const GET_TRENDING_TV_FAIL = 'GET_TRENDING_TV_FAIL';

export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';

export const GET_TV_SUCCESS = 'GET_TV_SUCCESS';
export const GET_TV_START = 'GET_TV_START';
export const GET_TV_FAIL = 'GET_TV_FAIL';

export const GET_CARD_DETAILS_SUCCESS = 'GET_CARD_DETAILS_SUCCESS';
export const GET_CARD_DETAILS_START = 'GET_CARD_DETAILS_START';
export const GET_CARD_DETAILS_FAIL = 'GET_CARD_DETAILS_FAIL';